#!/bin/bash

# Set up environment variable so that files are looped though correctly
OIFS="$IFS"
IFS=$'\n' 

# List all the ways to convert series names:

# pretty.little.liars ==> Pretty Little Liars S02E06.avi
type[0]="s/.*\([S][0-9]*[E][0-9]*\).*\(\.[0-9a-zA-Z]\{3\}$\)/$1 \1\2/"

# FUT416 - Three Hundred Big Boys.mp4 ==> Futurama S04E16.mp4
type[1]="s/.*\([0-9]\)\([0-9]\{2\}\).*\(\.[0-9a-zA-Z]\{3\}$\)/$1 S0\1E\2\3/"

# 5x03 - What Is And What Should Never Be.avi ==> That 70's Show S05E03.avi
type[2]="s/.*\([0-9]\)[x]\([0-9]\{2\}\).*\(\.[0-9a-zA-Z]\{3\}$\)/$1 S0\1E\2\3/"

# 11 - Good Old Fashioned Lover Boy.avi ==> That 70's Show S08E11.avi
type[3]="s/.*\([0-9]\{2\}\).*\(\.[0-9a-zA-Z]\{3\}$\)/$1E\1\2/"

# Prompt user
echo "Renames to do:"
echo $1

# Start with type[0]
i=0

# Determine type to use
while :
do
    for file in $(find . -type f)
    do
        if [ ! $file == "." ]; then
            echo "$file ==> $(echo $file | sed "${type[i]}")"
        fi
    done
    echo "Is this correct?"
    read correct
    if [[ $correct == "y" ]]; then
        break
    fi
    i=$(($i+1))
done

echo "Do you want to do these renames?  [y/n]"
read rename

if [[ $rename == "y" ]]; then
    for file in $(find . -type f)
    do
        if [ ! $file == "." ]; then
            mv $file "$(echo $file | sed "${type[i]}")"
        fi
    done
else
    echo "Aborted"
fi

# Set environment variable back to normal
IFS="$OIFS"
